---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-metrics
  namespace: dev
  annotations:
    flux.weave.works/tag.podinfod: glob:*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-metics
  template:
    metadata:
      labels:
        app: demo-metics
    spec:
      containers:
      - name: demo-metics
        image: quay.io/brice/metrics-demo:v4-subscription-service
        ports:
        - containerPort: 3000
